version: '3.5'

services:
  tomcat:
    image: tomcat
    container_name: tom
    restart: always
    volumes:
        # add user for web management interface
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
        # remove IP address restriction and allow connections from anywhere
      - ./context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
    ports:
      - $TOMCAT_PORT:8080
    networks:
      - java-examples

  maven:
    image: maven
    container_name: mav
    restart: always
    command: tail -f /dev/null # keep the container running in background
    working_dir: /examples
    volumes:
      - ../examples:/examples
      - ../scripts/maven.sh:/maven.sh
        # reuse local Maven repository
      - $HOME/.m2/repository:/root/.m2/repository
        # add deployment credentials
      - ./settings.xml:/usr/share/maven/ref/settings.xml
    ports:
      - $MAVEN_PORT:8080
    networks:
      - java-examples

  db:
    image: postgres
    container_name: pos
    restart: always
    environment:
        POSTGRES_USER: $DB_USER
        POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - ../scripts/dump.sql:/dump.sql
    ports:
      - $DB_PORT:5432
    networks:
      - java-examples

  adminer:
    image: adminer
    container_name: adm
    restart: always
    ports:
      - $ADMINER_PORT:8080
    networks:
      - java-examples

networks:
  java-examples:
    name: java-examples